### ISSUE TITLE
TCP socket close behaviour has changed

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-chrome#90]
I'm running Chrome 53.0.2785.116 on Linux.

Consider a simple programme which:
 * creates a client socket
 * connects to some server
 * immediately closes that socket

Two issues:
 1. unchecked `runtime.lastError` in the javascript console (it comes from `dispatchDisconnect`: https://github.com/freedomjs/freedom-for-chrome/blob/master/providers/core.tcpsocket.js#L419)
 1. `dispatchDisconnect` dispatches the wrong `errcode`: `CONNECTION_CLOSED`, when it should be `SUCCESS` (the problem is Chrome is returning -100 rather than 0 to `handleReadError`: https://github.com/freedomjs/freedom-for-chrome/blob/master/providers/core.tcpsocket.js#L519)

**Comment by soycode** [comment]
All the tests (unit/integration) still pass in Chrome 53, so it would probably be good to add a test that illustrates this issue. My attempt at this - https://github.com/freedomjs/freedom/commit/264d9b2eec6ef5732c6b46809183357d8f0fe9a9

I see both issues, in fact the unchecked `runtime.lastError` seems to pop up several times across tests, though it doesn't actually break any other tests. The `errcode` is indeed incorrect, though.

Let me know if this looks to capture what you're getting at and I'll investigate fixing it. Thanks!

PS - this test does seem to pass in Firefox, so that's good at least.

**Comment by soycode** [comment]
Logging and poking around (https://github.com/freedomjs/freedom-for-chrome/commit/90b43cd41be2c097543459934c6cc087e21e2922) has verified that Chrome is indeed raising an error w/code -100 immediately after the native `.close` is invoked (https://developer.chrome.com/apps/sockets_tcp#method-close).

It'd be pretty easy to just catch and change this specific error into a success, but I'm unsure if that's just covering up an actual issue. That said, if this is an actual issue then the fix might be Chrome-side as this bit of code is a pretty minimal wrapper/invocation of the sockets API, and the error is native and happens immediately after invoking a native method.

Let me know if you're okay with just smoothing out the error on our end and forcing it to be a SUCCESS in this case, or if you have any other thoughts. Thanks!

**Comment by soycode** [comment]
To document here - we went with the "paper it over" approach for now, with the possibility of filing an issue w/Chrome in future. The pull requests linked above handle the issue for now.
